defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed

url: https://oneforalone.github.io
author: Yuqi Liu
