defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"

gitalk:
  enable: true
  owner: oneforalone
  repo: oneforalone.github.io
  client_id: 09f241a9cc2e1a00df46
  clientSecret: 599353d0e49ac81733977f0bcd0ec4c1edae5e6f